### PR TITLE
yoshino: Welcome to the family poplar_canada, eh?

### PR DESCRIPTION
**Pull request by derfelot**

### CODE REVIEW

**Comment by sjllls** [comment]
@derfelot  @cryptomilk 
Hi, I meet a problem when building lineageOS 16 for XZ2. But I can't find the problem.  Now I stuck at LineageOS logo with endless animation. Could you please do me a favor ? Thanks a lot!
[xz2-los16.txt](https://github.com/cryptomilk/android_device_sony_yoshino/files/3751962/xz2-los16.txt)

**Comment by cryptomilk** [comment]
Isn't hat obvious at the first look?

```
F linker  : CANNOT LINK EXECUTABLE "/vendor/bin/hw/android.hardware.wifi@1.0-service": library "android.hardware.wifi@1.0.so" not found
```

**Comment by cryptomilk** [comment]
Fix all CANNOT LINK EXECUTABLE issues ...

**Comment by derfelot** [comment]
yes, almost looks like you don't have a manifest at all?

**Comment by sjllls** [comment]
@cryptomilk Yes, it look obvious. My tree is modified from Oneplus 6T, it didn't build a vendor image. It uses official vendor image and only build a boot and system images. So it should not lack of any blobs on vendor partition.

**Comment by sjllls** [comment]
@cryptomilk Is copying the so files to the target system partition right way to fix CANNOT LINK EXECUTABLE ?

**Comment by sjllls** [comment]
@derfelot I also noticed these in log. But after I added it in COMPATIBILITY_MATRIX.xml, the log also tell me no entry for these Hals in manifest.

**Pull request merged**
