### PR TITLE
overlay: Allow call recording for dialer app

### PR DESCRIPTION
**Pull request by sjllls**

### CODE REVIEW

**Comment by derfelot** [comment]
AFAIK, this is already handled on a country-by-country basis in los (based in the mcc value) depending on local laws:

https://github.com/LineageOS/android_packages_apps_Dialer/tree/lineage-16.0/java/com/android/dialer/callrecord/res

I don't think we really want to override this.

**Comment by derfelot** [comment]
OK, so i looked at it again, and it might be that the logic is different here. so by default call recording is completely off in los. I guess this overlay would allow it, _unless_ an mcc-specifc entry exists that will switch it off again. but not entirely sure.

**Comment by sjllls** [comment]
> OK, so i looked at it again, and it might be that the logic is different here. so by default call recording is completely off in los. I guess this overlay would allow it, _unless_ an mcc-specifc entry exists that will switch it off again. but not entirely sure.

After using thsi overlay, callrecord is enabled and works fine.
Screenshot_20190522-230536_Phone

**Comment by derfelot** [comment]
That's good, but we need to verify that this doesn't get enabled in countries where it shouldn't be used. I will test this soon - where I am it is not supposed to work because it doesn't comply with local law.

**Comment by sjllls** [comment]
> That's good, but we need to verify that this doesn't get enabled in countries where it shouldn't be used. I will test this soon - where I am it is not supposed to work because it doesn't comply with local law.

In fact, the mmc configurations of Dialer in lineage is not complete.
4 stands for Asia and middle East, but Lineage's configuration include none of them.
I think we better not rely on it  before it is complete.
https://en.m.wikipedia.org/wiki/Mobile_country_code

**Comment by derfelot** [comment]
I haven't forgotten this :) Will test this weekend still.

**Comment by sjllls** [comment]
> I haven't forgotten this :) Will test this weekend still.

Thanks for your effort. 
 I meet so many troble in building Los16.0 on maple. Some libs failed to be loaded.
[maple-eng.log](https://github.com/cryptomilk/android_device_sony_yoshino/files/3243796/maple-eng.log)

EAS finnaly work on a stable status but still not as well as HMP.
photo6271290523411130567

**Comment by derfelot** [comment]
About the maple log, I already replied to your PM on xda. Try to get a 'dmesg' or 'logcat -b all'. Otherwise you can use the hack to log to /cache.

**Comment by derfelot** [comment]
actually, looking at the logs, i think the issue here is vndk. IIRC, maple doesn't come with its own /vendor partition, right? You could try to revert these two commits and see:

https://github.com/cryptomilk/android_device_sony_yoshino/commit/f272b623fde131fbf701361a944ec29a10bea436#diff-2e9712b5ed713bf372a83cc477f59a2a

https://github.com/cryptomilk/android_device_sony_common-treble/commit/02da91279f8defe7978a02eda7cbe9c849b3bc8e#diff-a0695b0f6424f6cb0b77dd917074a2c6

**Comment by sjllls** [comment]
> actually, looking at the logs, i think the issue here is vndk. IIRC, maple doesn't come with its own /vendor partition, right? You could try to revert these two commits and see:
> 
> [f272b62#diff-2e9712b5ed713bf372a83cc477f59a2a](https://github.com/cryptomilk/android_device_sony_yoshino/commit/f272b623fde131fbf701361a944ec29a10bea436#diff-2e9712b5ed713bf372a83cc477f59a2a)
> 
> [cryptomilk/android_device_sony_common-treble@02da912#diff-a0695b0f6424f6cb0b77dd917074a2c6](https://github.com/cryptomilk/android_device_sony_common-treble/commit/02da91279f8defe7978a02eda7cbe9c849b3bc8e#diff-a0695b0f6424f6cb0b77dd917074a2c6)

Yes, Maple doesn't have vendor partition. But VNDK should be enabled on stock, I found the vndk folder and libs in stock system partition.
Let me try and rebuild again.

**Comment by sjllls** [comment]
> actually, looking at the logs, i think the issue here is vndk. IIRC, maple doesn't come with its own /vendor partition, right? You could try to revert these two commits and see:
> 
> [f272b62#diff-2e9712b5ed713bf372a83cc477f59a2a](https://github.com/cryptomilk/android_device_sony_yoshino/commit/f272b623fde131fbf701361a944ec29a10bea436#diff-2e9712b5ed713bf372a83cc477f59a2a)
> 
> [cryptomilk/android_device_sony_common-treble@02da912#diff-a0695b0f6424f6cb0b77dd917074a2c6](https://github.com/cryptomilk/android_device_sony_common-treble/commit/02da91279f8defe7978a02eda7cbe9c849b3bc8e#diff-a0695b0f6424f6cb0b77dd917074a2c6)

After reverting the two commits.
[dmesg.txt](https://github.com/cryptomilk/android_device_sony_yoshino/files/3244521/dmesg.txt)
[logcat.txt](https://github.com/cryptomilk/android_device_sony_yoshino/files/3244523/logcat.txt)
[logcat-all.txt](https://github.com/cryptomilk/android_device_sony_yoshino/files/3244524/logcat-all.txt)

**Comment by derfelot** [comment]
[ 2.554777] init: Unable to read config file '/system/etc/init/gsi/init.vndk-28.rc': open() failed: No such file or directory [ 2.554786] init: /init.rc: 2: Could not import file '/system/etc/init/gsi/init.vndk-28.rc': No such file or directory

you could try to replace the three instances of 27 by 28 here: https://github.com/cryptomilk/android_device_sony_common-treble/commit/02da91279f8defe7978a02eda7cbe9c849b3bc8e#diff-a0695b0f6424f6cb0b77dd917074a2c6

**Comment by derfelot** [comment]
you can probably remove PRODUCT_EXTRA_VNDK_VERSIONS completely actually

**Comment by sjllls** [comment]
> [ 2.554777] init: Unable to read config file '/system/etc/init/gsi/init.vndk-28.rc': open() failed: No such file or directory [ 2.554786] init: /init.rc: 2: Could not import file '/system/etc/init/gsi/init.vndk-28.rc': No such file or directory
> 
> you could try to replace the three instances of 27 by 28 here: [cryptomilk/android_device_sony_common-treble@02da912#diff-a0695b0f6424f6cb0b77dd917074a2c6](https://github.com/cryptomilk/android_device_sony_common-treble/commit/02da91279f8defe7978a02eda7cbe9c849b3bc8e#diff-a0695b0f6424f6cb0b77dd917074a2c6)

build/make/core/envsetup.mk:345: error: VNDK version 28 not found.

I changed it to:
```
# Support for the O-MR1 devices
PRODUCT_COPY_FILES += \
    build/make/target/product/vndk/init.gsi.rc:system/etc/init/init.gsi.rc \
    build/make/target/product/vndk/init.vndk-27.rc:system/etc/init/gsi/init.vndk-28.rc

# Name space configuration file for non-enforcing VNDK
PRODUCT_PACKAGES += \
    ld.config.vndk_lite.txt

# Support addtional O-MR1 vendor interface
PRODUCT_EXTRA_VNDK_VERSIONS := 27
```

**Comment by sjllls** [comment]
> you can probably remove PRODUCT_EXTRA_VNDK_VERSIONS completely actually

It still can't load the libs.
Let me remove all the configs of VNDK and rebuild.

**Comment by derfelot** [comment]
OK, I tested this change and it does not enable call recording here (as intended). so should be good to merge.

**Comment by sjllls** [comment]
> OK, I tested this change and it does not enable call recording here (as intended). so should be good to merge.

Thanks for your test.

**Comment by cryptomilk** [comment]
Thanks for your contribution!

**Pull request merged**
